# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FLReader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FLReader
pod 'AFNetworking','~>3.0'
pod 'Masonry'

  target 'FLReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FLReaderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
